### PR TITLE
Add support for Jinja2 extensions and custom preprocessors (2)

### PR DESCRIPTION
**Pull request by stucox**
Repeat of #169, rebased & raised against `develop`.

---

Simple solution for #55. A slight variation on what I proposed there: decided it was easier & more explicit to separate jinja2 / preprocessors in podspec.yaml:

```yaml
extensions:
  jinja2:
  - path.to.CustomJinja2Extension
  preprocessors:
  - path.to.CustomPreprocessor
```

[See the example in grow/testing/testdata/pod/podspec.yaml](https://github.com/stucox/pygrow/blob/feature/extensions/grow/testing/testdata/pod/podspec.yaml#L54).

Custom Jinja2 filters would need to be wrapped in an extension class (i.e. a subclass of) — the tests I’ve written for this include an example of this. Could add syntax to allow filters to be declared directly in podspec.yaml (then added to the env via the `filters` arg) — maybe at a later date?

Happy to write some docs for this once merged — should that be a PR against https://github.com/grow/growsdk.org?

---

@jeremydw said:

> Great work on this and thank you for the contribution. :) The solution looks great from a quick glance.
>
> Before merging, I'm doing a tiny bit of research on naming and the syntax in podspec.yaml. Can you adjust the PR to be based off of develop instead of master? master is what's currently released.

Done.

> Also, before releasing this I'd like to perhaps iterate on the "public API" for writing extensions -- for example, it might be cleaner to allow import grow and then for the base class to be grow.Preprocessor (via an alias in the right place in \_\_init\_\_.py). This would basically be the first time the internal paths of the Python program have any implication on how folks construct sites.

I’ve added an alias as suggested — agree this makes sense to keep flexibility over internal structure.

Appreciate the Preprocessor class API might need refining too, but how about we leave this as-is, undocumented (or mark “experimental”) for now and try it out ourselves?

> Additionally (just as a reminder to myself) – need to test the behavior of the imports in the frozen/binary environment.

Ok sure, let me know if I can help.

### CODE REVIEW

**Comment by jeremydw** [comment]
Thanks Stu! Will take another close look towards the end of the week. I'll
likely pull this into develop and then make that quick change to adjust the
base class from there.

On Mon, Feb 15, 2016 at 2:37 AM, Stu Cox <notifications@github.com> wrote:

> Repeat of #169 <https://github.com/grow/pygrow/pull/169>, rebased &
> raised against develop.
> ------------------------------
>
> Simple solution for #55 <https://github.com/grow/pygrow/issues/55>. A
> slight variation on what I proposed there: decided it was easier & more
> explicit to separate jinja2 / preprocessors in podspec.yaml:
>
> extensions:
>   jinja2:
>   - path.to.CustomJinja2Extension
>   preprocessors:
>   - path.to.CustomPreprocessor
>
> See the example in grow/testing/testdata/pod/podspec.yaml
> <https://github.com/stucox/pygrow/blob/feature/extensions/grow/testing/testdata/pod/podspec.yaml#L54>
> .
>
> Custom Jinja2 filters would need to be wrapped in an extension class (i.e.
> a subclass of) — the tests I’ve written for this include an example of
> this. Could add syntax to allow filters to be declared directly in
> podspec.yaml (then added to the env via the filters arg) — maybe at a
> later date?
>
> Happy to write some docs for this once merged — should that be a PR
> against https://github.com/grow/growsdk.org?
> ------------------------------
>
> @jeremydw <https://github.com/jeremydw> said:
>
> Great work on this and thank you for the contribution. :) The solution
> looks great from a quick glance.
>
> Before merging, I'm doing a tiny bit of research on naming and the syntax
> in podspec.yaml. Can you adjust the PR to be based off of develop instead
> of master? master is what's currently released.
>
> Done.
>
> Also, before releasing this I'd like to perhaps iterate on the "public
> API" for writing extensions -- for example, it might be cleaner to allow
> import grow and then for the base class to be grow.Preprocessor (via an
> alias in the right place in *init*.py). This would basically be the first
> time the internal paths of the Python program have any implication on how
> folks construct sites.
>
> I’ve added an alias as suggested — agree this makes sense to keep
> flexibility over internal structure.
>
> Appreciate the Preprocessor class API might need refining too, but how
> about we leave this as-is, undocumented (or mark “experimental”) for now
> and try it out ourselves?
>
> Additionally (just as a reminder to myself) – need to test the behavior of
> the imports in the frozen/binary environment.
>
> Ok sure, let me know if I can help.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/grow/pygrow/pull/175
> Commit Summary
>
>    - Add support for custom Jinja2 extensions
>    - Add support for custom preprocessors
>    - Add alias to allow `from grow import Preprocessor` to avoid coupling
>    to internal structure
>
> File Changes
>
>    - *M* grow/__init__.py
>    <https://github.com/grow/pygrow/pull/175/files#diff-0> (3)
>    - *M* grow/common/utils.py
>    <https://github.com/grow/pygrow/pull/175/files#diff-1> (15)
>    - *M* grow/pods/controllers/rendered_test.py
>    <https://github.com/grow/pygrow/pull/175/files#diff-2> (6)
>    - *M* grow/pods/pods.py
>    <https://github.com/grow/pygrow/pull/175/files#diff-3> (18)
>    - *M* grow/pods/pods_test.py
>    <https://github.com/grow/pygrow/pull/175/files#diff-4> (31)
>    - *M* grow/pods/preprocessors/preprocessors.py
>    <https://github.com/grow/pygrow/pull/175/files#diff-5> (7)
>    - *A* grow/testing/testdata/pod/extensions/__init__.py
>    <https://github.com/grow/pygrow/pull/175/files#diff-6> (0)
>    - *A* grow/testing/testdata/pod/extensions/preprocessors.py
>    <https://github.com/grow/pygrow/pull/175/files#diff-7> (13)
>    - *A* grow/testing/testdata/pod/extensions/triplicate.py
>    <https://github.com/grow/pygrow/pull/175/files#diff-8> (12)
>    - *M* grow/testing/testdata/pod/podspec.yaml
>    <https://github.com/grow/pygrow/pull/175/files#diff-9> (11)
>    - *M* grow/testing/testdata/pod/views/home.html
>    <https://github.com/grow/pygrow/pull/175/files#diff-10> (3)
>    - *M* requirements.txt
>    <https://github.com/grow/pygrow/pull/175/files#diff-11> (1)
>
> Patch Links:
>
>    - https://github.com/grow/pygrow/pull/175.patch
>    - https://github.com/grow/pygrow/pull/175.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grow/pygrow/pull/175>.
>



-- 
jeremydw

**Comment by jeremydw** [comment]
Okay, I've sat on this long enough and I think the solution is really elegant and simple. Thank you for sending this in. I'll merge this now to develop.

We should also add support for `grow.Preprocessor` (versus `grow.preprocessors.Preprocessor`) and update the base class used in the pod's preprocessor testdata to simplify the API for folks that want to write custom preprocessors. Just like Jinja2's `jinja2.Environment` – `grow.Preprocessor` will be nice and short and easy to remember when writing preprocessors.

**Comment by stucox** [comment]
FYI I've already added the `grow.Preprocessor ` import shorthand: https://github.com/stucox/pygrow/blob/dc5e43349f024222a13b55bd57ebf285a98baa88/grow/__init__.py

**Comment by jeremydw** [comment]
Cheers, you did. Thank you! This will make it into our next release, which I think we should release next week.

I'd like to add some docs too. I think it deserves a new top-level page on the documentation site. Is writing the docs something you'd be interested in doing or should I take a stab at them next week? Thank you.

**Comment by jeremydw** [comment]
Took an initial stab at the docs –

Preview: http://grow.io/docs/extensions/
Sources: https://github.com/grow/growsdk.org/edit/master/content/docs/extensions.md

Thanks for your work on this – feel free to propose any changes to the docs!

**Pull request merged**
